### ISSUE TITLE
Some biomes still not spawning

### ISSUE THREAD

**Issue by DeadPigman17** [AOCAWOL/BYG#37]
All beach biomes and the tropical island biome don't spawn, even when I have no other mods installed and I'm using the default world type.
Also, when using Biomes o plenty, nether biomes from BYG don't spawn.

**Comment by AOCAWOL** [comment]
Nether biomes with BOP is because BOP overrides and locks the nether that is on their end. With the tropical islands and beach biomes, these biomes were exclusive to our BYG World Type that has been temp. removed while it's being fixed. These biomes cannot spawn in the default world type because MC doesn't have a way to add Island Biomes to the world. Tropical Islands would just spawn as a normal biome in default.
